'use strict';

// COMPATIBILITY NOTE: This file is copied into Memento's pipeline directory
// during installation. Fresh installs require pipeline_config.json to exist
// (generated by the onboarding flow). Legacy installs without a config file
// will get null/empty returns instead of owner-specific fallbacks.

const fs = require('fs');
const path = require('path');

const CONFIG_PATH = path.join(__dirname, '../../state/runtime/pipeline_config.json');

const DEFAULT_GMAIL_FILTERS = {
  skip_categories: ['promotions', 'social', 'forums'],
  skip_calendar_invites: true,
  personal_noise_accounts: [],
};

function loadPipelineConfig(configPath) {
  const resolvedPath = configPath || CONFIG_PATH;
  try {
    return JSON.parse(fs.readFileSync(resolvedPath, 'utf8'));
  } catch (_) {
    return null;
  }
}

function getGmailAccounts(configPath) {
  const config = loadPipelineConfig(configPath);
  const accounts = config?.accounts?.gmail;
  if (Array.isArray(accounts) && accounts.length > 0) {
    const mapped = {};
    for (const account of accounts) {
      if (account?.name && account?.config_dir) {
        mapped[account.name] = account.config_dir;
      }
    }
    if (Object.keys(mapped).length > 0) return mapped;
  }
  return {};
}

function getBasecampApiBase(configPath) {
  const config = loadPipelineConfig(configPath);
  return config?.accounts?.basecamp?.api_base || null;
}

function getCalendarConfig(configPath) {
  const config = loadPipelineConfig(configPath);
  const calendarConfig = config?.accounts?.calendar || {};
  const primaryEmail = config?.owner?.emails?.[0] || null;
  const calendarIds = Array.isArray(calendarConfig.calendars) && calendarConfig.calendars.length > 0
    ? calendarConfig.calendars
    : (primaryEmail ? [primaryEmail] : []);
  return {
    calendarIds,
    configDir: calendarConfig.config_dir || null,
  };
}

function getDriveConfigDir(configPath) {
  const config = loadPipelineConfig(configPath);
  return config?.accounts?.drive?.config_dir || null;
}

function getGmailFilters(configPath) {
  const config = loadPipelineConfig(configPath);
  return {
    ...DEFAULT_GMAIL_FILTERS,
    ...(config?.gmail_filters || {}),
  };
}

module.exports = {
  CONFIG_PATH,
  DEFAULT_GMAIL_FILTERS,
  loadPipelineConfig,
  getGmailAccounts,
  getBasecampApiBase,
  getCalendarConfig,
  getDriveConfigDir,
  getGmailFilters,
};
